FROM python:3.11-slim

# Устанавливаем системные зависимости, необходимые для python-docx и asyncpg
RUN apt-get update && \
    apt-get install -y gcc libpq-dev && \
    rm -rf /var/lib/apt/lists/*

# Указываем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файлы зависимостей заранее (для быстрого layer cache)
COPY requirements.txt .

# Устанавливаем python-зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем всё приложение в рабочую директорию (исключая dockerignore)
COPY ./app ./app

# Создаем папку, если нужно (shared_data монтируется volume, но на всякий случай)
RUN mkdir -p /shared_data

# Открываем порт
EXPOSE 8000

# Переменная среды для prod (опционально)
ENV PYTHONUNBUFFERED=1

# Стартуем FastAPI через uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
